language: python

dist: xenial

os:
  - linux

# If you need gcc or other non python packages and libraries
#addons:
#  apt_packages:
#    - gfortran
#    - swig
#    - libhdf5-serial-dev

python:
  - '3.5'
  - '3.6'
  - '3.7'

before_install:
  - pip install pip setuptools --upgrade

install:
  - python -m pip install .[doc]

before_script:
  - python -m pip install coveralls coverage codecov "pytest>=3.1" pytest-runner

script:
  # run unit tests
  - coverage run ./setup.py test

  # build documentation
  - cd docs && make html; cd ../

after_success:
  - coveralls
  - codecov

cache:
  pip: true
  apt: true
